name: Build and Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    # Build and test debug build with ASAN and NOCRYPTO 
    - name: Build and test ASAN DEBUG
      run: cd test && make DEBUG=1 ASAN=1 NOCRYPTO=1 WOLFSSL_DIR=../wolfssl run

    # Build and test debug build with ASAN 
    - name: Build and test ASAN DEBUG
      run: cd test && make DEBUG=1 ASAN=1 WOLFSSL_DIR=../wolfssl run

    # Build and test debug build with SHE 
    - name: Build and test SHE DEBUG
      run: cd test && make DEBUG=1 SHE=1 WOLFSSL_DIR=../wolfssl run
          
    # Build and test standard build
    - name: Build and test
      run: cd test && make WOLFSSL_DIR=../wolfssl run

